os: osx

before_install:
  - brew update
install:
  - git clone https://github.com/thinca/vim-themis --quiet --branch v1.5.3 --single-branch --depth 1 ~/vim-themis
  - git clone https://github.com/vim-jp/vital.vim --depth 1 ~/.vim/pack/test/opt/vital.vim
  - git clone https://github.com/haya14busa/vital-vimlcompiler --depth 1 ~/.vim/pack/test/opt/vital-vimlcompiler
  - git clone https://github.com/haya14busa/vital-safe-string --depth 1  ~/.vim/pack/test/opt/vital-safe-string
  - git clone https://github.com/haya14busa/vital-power-assert --depth 1 ~/.vim/pack/test/opt/vital-power-assert
  - git clone https://github.com/vim/vim.git ~/vim --depth 1 --branch v8.0.0039
  - brew install fzy
  - cd ~/vim && ./configure --with-features=huge --enable-multibyte && make -j4 && sudo make install
script:
  - cd ~/MaxMEllon/vim-fzy-rails && ~/vim-themis/bin/themis --reporter dot --runtimepath ${HOME}/.vim -r test
